POST https://routes.googleapis.com/directions/v2:computeRoutes
X-Goog-Api-Key: AIzaSyAbC9tpimj-DouwLuOE16EpvA2k10llwDg
X-Goog-FieldMask: routes.duration,routes.distanceMeters,routes.staticDuration,routes.description,routes.localizedValues.duration,routes.localizedValues.staticDuration,routes.localizedValues.distance
Content-Type: application/json

{
  "origin": {
    "address": "Sarnen"
  },
  "destination": {
    "address": "Zurich"
  },
  "travelMode": "DRIVE",
  "departureTime": "2023-09-18T05:01:23Z",
  "routingPreference": "TRAFFIC_AWARE_OPTIMAL",
  "trafficModel": "BEST_GUESS"
}

###

